# fly.toml app configuration file generated for aivocabulary on 2023-12-04T14:15:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aivocabulary"
primary_region = "ams"

[env]
  OPENAI_API_KEY   = "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"
  UNSPLASH_API_KEY = "-ANZSgOmVhSxrDesaO8DHO2SGIi73Ylbyfxqi-RZvDA"


[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
