# fly.toml app configuration file generated for aivocabulary-icy-wildflower-8407-crimson-sound-9840-wild-leaf-1048-bold-voice-2294 on 2023-12-04T12:54:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aivocabulary-icy-wildflower-8407-crimson-sound-9840-wild-leaf-1048-bold-voice-2294"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
