version: '3.9'

services:
  voc_db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=LearnAlotOfLanguages
      - POSTGRES_DB=aivocabulary_db